#!/usr/bin/env bash
# Creates /var/run/myscript.pid, prints indefinitely, and handles signals

echo "$$" > /var/run/myscript.pid

sigterm() {
  echo "I hate the kill command"
  rm -f /var/run/myscript.pid
  exit 0
}

sigint() {
  echo "Y U no love me?!"
}

sigquit() {
  rm -f /var/run/myscript.pid
  exit 0
}

trap sigterm SIGTERM
trap sigint  SIGINT
trap sigquit SIGQUIT

while true; do
  echo "To infinity and beyond"
  sleep 2
done
