#!/usr/bin/env bash
# Display visitor IP and HTTP status code from Apache log
awk '
{
  ip = $1
  code = ""

  if (match($0, /" [0-9][0-9][0-9] /))
    code = substr($0, RSTART + 2, 3)

  if (ip ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && code ~ /^[0-9][0-9][0-9]$/)
    print ip, code
}' apache-access.log
