#!/usr/bin/env bash
# Group visitors by IP and HTTP status code
awk '$1 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && $9 ~ /^[0-9][0-9][0-9]$/ { c[$1" "$9]++ }
END { for (k in c) printf "%7d %s\n", c[k], k }' apache-access.log | sort -nr
